services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  fines-db:
    image: postgres:17
    container_name: fines-db
    environment:
      POSTGRES_DB: fines_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - fines-db-data:/var/lib/postgresql/data

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/config-repo
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=file:///config-repo

  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    depends_on:
      - config-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888

  fines-api:
    build: ./fines-api
    container_name: fines-api
    depends_on:
      - config-server
      - discovery-server
      - fines-db
      - rabbitmq
    ports:
      - "8081:8081"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fines-db:5432/fines_db
      - SPRING_RABBITMQ_HOST=rabbitmq

  library-db:
    image: postgres:17
    container_name: library-db
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "351909"
    ports:
      - "5435:5432"
    volumes:
      - library-db-data:/var/lib/postgresql/data

  library-api:
    build: ./library-api
    container_name: library-api
    depends_on:
      - config-server
      - discovery-server
      - library-db
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library-db:5432/library_db
      - SPRING_RABBITMQ_HOST=rabbitmq

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - config-server
      - discovery-server
      - library-api
      - fines-api
    ports:
      - "8082:8082"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://discovery-server:8761/eureka/

volumes:
  fines-db-data:
    external: true
    name: fines-db-data
  library-db-data: