apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fines-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fines-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fines-db
  template:
    metadata:
      labels:
        app: fines-db
    spec:
      containers:
        - name: fines-db
          image: postgres:17
          env:
            - name: POSTGRES_DB
              value: fines_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: fines-db-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: fines-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: fines-db-storage
          persistentVolumeClaim:
            claimName: fines-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: fines-db
spec:
  selector:
    app: fines-db
  ports:
    - port: 5432
      targetPort: 5432