apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-db
  template:
    metadata:
      labels:
        app: library-db
    spec:
      containers:
        - name: library-db
          image: postgres:17
          env:
            - name: POSTGRES_DB
              value: library_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: library-db-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: library-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: library-db-storage
          persistentVolumeClaim:
            claimName: library-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: library-db
spec:
  selector:
    app: library-db
  ports:
    - port: 5432
      targetPort: 5432