apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-api
  template:
    metadata:
      labels:
        app: library-api
    spec:
      containers:
        - name: library-api
          image: library-library-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://config-server:8888
            - name: EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://library-db:5432/library_db
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: library-api
spec:
  selector:
    app: library-api
  ports:
    - port: 8080
      targetPort: 8080